//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace StackingEntities.Desktop.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("StackingEntities.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your commands, one per line. We&apos;ll create a MinecartCommandBlock stack for you that will execute in order. (We recommend adding &amp;quot;kill @e[type=MinecartCommandBlock]&amp;quot; as your last command..
        /// </summary>
        internal static string CommandBlockWindow_Description {
            get {
                return ResourceManager.GetString("CommandBlockWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Entry.
        /// </summary>
        internal static string CommandBlockWindow_Title {
            get {
                return ResourceManager.GetString("CommandBlockWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string MainWindow_AboutTooltip {
            get {
                return ResourceManager.GetString("MainWindow_AboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MainWindow_Add {
            get {
                return ResourceManager.GetString("MainWindow_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string MainWindow_Copy {
            get {
                return ResourceManager.GetString("MainWindow_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Summon.
        /// </summary>
        internal static string MainWindow_GenerateSummon {
            get {
                return ResourceManager.GetString("MainWindow_GenerateSummon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Commands....
        /// </summary>
        internal static string MainWindow_ListOfCommands {
            get {
                return ResourceManager.GetString("MainWindow_ListOfCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc. Tools.
        /// </summary>
        internal static string MainWindow_MiscToolsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_MiscToolsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft Entity Stacker.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Entities.
        /// </summary>
        internal static string StackedEntities_Header {
            get {
                return ResourceManager.GetString("StackedEntities_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon Options.
        /// </summary>
        internal static string SummonOptions_Header {
            get {
                return ResourceManager.GetString("SummonOptions_Header", resourceCulture);
            }
        }
    }
}
